### PR TITLE
Version 5.4

### PR DESCRIPTION
**Pull request by ameennihad**
Please check changelog.txt for list of new features and fixes.

### CODE REVIEW

**Comment by ameennihad** [comment]
Just noticed a bug in pads diameter, it's due to "this" "that" conflict, shall I do another pull request or you can fix it? following is the code that requires change (starting at line 6669):
`var diameter;`
`if (that.activeLayer == "Top")`
`diameter = pad.diameterTop;`
 `else if (that.activeLayer == "Bottom")`                   
 `diameter = pad.diameterbottom;`

**Comment by chilipeppr** [comment]
Hmm. I could try to keep this note in the back of my head, but a pull
request could help me make sure I don't miss it.

**Comment by ameennihad** [comment]
I believe the fix is automatically pushed to this request.

**Comment by chilipeppr** [comment]
Ok, cool.

**Pull request merged**
